### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: de/lmu/ifi/dbs/jfeaturelib/features/SURF

### ISSUE THREAD

**Issue by Divyam53** [locked-fg/JFeatureLib-Demo#2]
cd C:\Users\D\Documents\NetBeansProjects\ContentBasedImageRetrieval; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_121" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath Surf\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_121\\bin\\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar;C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-cos.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building ContentBasedImageRetrieval 1.0-SNAPSHOT
------------------------------------------------------------------------
The POM for net.semanticmetadata:lire:jar:0.9.4-fg-SNAPSHOT is missing, no dependency information available

--- exec-maven-plugin:1.2.1:exec (default-cli) @ ContentBasedImageRetrieval ---
Exception in thread "main" java.lang.NoClassDefFoundError: de/lmu/ifi/dbs/jfeaturelib/features/SURF
	at Surf.main(Surf.java:22)
Caused by: java.lang.ClassNotFoundException: de.lmu.ifi.dbs.jfeaturelib.features.SURF
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.272s
Finished at: Sun Jun 18 12:07:39 IST 2017
Final Memory: 5M/123M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project ContentBasedImageRetrieval: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Divyam53** [comment]
Resolved, i was having this issue because i have imported the project 'JFeatureLib', and at the runtime, it was searching the class in that project and i haven't compiled 'JFeatureLib'
